
package org.socraticgrid.kmr.knowledgemodule;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.socraticgrid.kmr.kmtypes.FindKmIdsResponseType;
import org.socraticgrid.kmr.kmtypes.KmIdSearchRequestType;
import org.socraticgrid.kmr.kmtypes.KmIdSearchResponseType;
import org.socraticgrid.kmr.kmtypes.KmImportRequestType;
import org.socraticgrid.kmr.kmtypes.KmLatestLogicResponseType;
import org.socraticgrid.kmr.kmtypes.KmMetaResponseType;
import org.socraticgrid.kmr.kmtypes.KmRequestType;
import org.socraticgrid.kmr.kmtypes.KmResponseType;
import org.socraticgrid.kmr.kmtypes.KmResponseTypeImportAck;
import org.socraticgrid.kmr.kmtypes.ObjectFactory;
import org.socraticgrid.kmr.kmtypes.ReferenceDataRefRequestType;
import org.socraticgrid.kmr.kmtypes.ReferenceDataRefResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3.1-hudson-749-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "KnowledgeModulePortType", targetNamespace = "urn:org:socraticgrid:kmr:knowledgemodule")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KnowledgeModulePortType {


    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.ReferenceDataRefResponseType
     */
    @WebMethod(operationName = "GetKmRefData", action = "urn:GetKmRefData")
    @WebResult(name = "GetRefDataResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public ReferenceDataRefResponseType getKmRefData(
        @WebParam(name = "GetRefDataRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        ReferenceDataRefRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmResponseType
     */
    @WebMethod(operationName = "GetKmByParams", action = "urn:GetKmByParams")
    @WebResult(name = "KmRecordResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmResponseType getKmByParams(
        @WebParam(name = "KmRecordRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmMetaResponseType
     */
    @WebMethod(operationName = "GetKmMeta", action = "urn:GetKmMeta")
    @WebResult(name = "GetKmMetaResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmMetaResponseType getKmMeta(
        @WebParam(name = "GetKmMetaRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmIdSearchRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmLatestLogicResponseType
     */
    @WebMethod(operationName = "GetKmLatestLogic", action = "urn:GetKmLatestLogic")
    @WebResult(name = "GetKmLatestLogicResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmLatestLogicResponseType getKmLatestLogic(
        @WebParam(name = "GetKmLatestLogicRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmIdSearchRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.FindKmIdsResponseType
     */
    @WebMethod(operationName = "FindKmId", action = "urn:FindKmId")
    @WebResult(name = "FindKmIdsResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public FindKmIdsResponseType findKmId(
        @WebParam(name = "FindKmIdsRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmIdSearchResponseType
     */
    @WebMethod(operationName = "GetKmById", action = "urn:GetKmById")
    @WebResult(name = "KmIdSearchResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmIdSearchResponseType getKmById(
        @WebParam(name = "KmIdSearchRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmIdSearchRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmResponseType
     */
    @WebMethod(operationName = "GetKmByParams_runtime", action = "urn:RuntimeDiscovery")
    @WebResult(name = "KmRuntimeRecordResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmResponseType getKmByParamsRuntime(
        @WebParam(name = "KmRuntimeRecordRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmResponseTypeImportAck
     */
    @WebMethod(operationName = "InsertKms", action = "urn:InsertKms")
    @WebResult(name = "KmInsertAckResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmResponseTypeImportAck insertKms(
        @WebParam(name = "KmInsertRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmImportRequestType param0);

    /**
     * 
     * @param param0
     * @return
     *     returns org.socraticgrid.kmr.kmtypes.KmResponseTypeImportAck
     */
    @WebMethod(operationName = "UpdateKms", action = "urn:UpdateKms")
    @WebResult(name = "KmUpdateAckResponse", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "output")
    public KmResponseTypeImportAck updateKms(
        @WebParam(name = "KmUpdateRequest", targetNamespace = "urn:org:socraticgrid:kmr:kmtypes", partName = "param0")
        KmImportRequestType param0);

}
